import { chromium } from '/opt/node-tools/node_modules/playwright-core/index.mjs'
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args:['--no-sandbox'] })
const p = await b.newPage({ viewport:{width:1280,height:900} })
const errs=[]; p.on('pageerror',e=>errs.push(e.message))
await p.goto('http://localhost:4180/', {waitUntil:'networkidle'})
await p.waitForTimeout(1000)
await p.screenshot({path:'/home/claude/work/shots/shell-overview.png'})
console.log('rail items :', await p.locator('.ma-rail a').count())
console.log('groups     :', (await p.locator('.ma-rail .grp').allTextContents()).join(' | '))
console.log('cards      :', await p.locator('.ma-card').count())
console.log('chips      :', (await p.locator('.rolechip').allTextContents()).join(' | '))
await p.locator('.ma-rail a', {hasText:'Certifications'}).click(); await p.waitForTimeout(700)
console.log('hash       :', new URL(p.url()).hash)
console.log('heading    :', (await p.locator('.ma-main h1').textContent())?.trim())
await p.screenshot({path:'/home/claude/work/shots/shell-tab.png'})
await p.locator('.ma-rail a', {hasText:'Roles'}).click(); await p.waitForTimeout(800)
console.log('roles page :', (await p.locator('.ma-main h1').textContent())?.trim())
await p.screenshot({path:'/home/claude/work/shots/shell-roles.png'})
const m = await b.newPage({ viewport:{width:390,height:844} })
await m.goto('http://localhost:4180/', {waitUntil:'networkidle'}); await m.waitForTimeout(800)
console.log('mobile hscroll:', await m.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth+1))
await m.screenshot({path:'/home/claude/work/shots/shell-mobile.png'})
console.log('page errors:', errs.length?errs.slice(0,3):'none')
await b.close()
